// In-memory хранилище для объявлений

let items = [
  {
    id: 0,
    name: "Репетитор по математике",
    description: "Подготовка к ЕГЭ и ОГЭ",
    location: "Новосибирск",
    type: "Услуги",
    serviceType: "Образование",
    experience: 6,
    cost: 1200,
  },
  {
    id: 1,
    name: "Квартира в центре",
    description: "Просторная квартира с видом на парк",
    location: "Москва",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 85,
    rooms: 3,
    price: 12000000,
  },
  {
    id: 2,
    name: "Загородный дом",
    description: "Уютный дом с садом и бассейном",
    location: "Подмосковье",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 150,
    rooms: 5,
    price: 25000000,
  },
  {
    id: 3,
    name: "Офисное помещение",
    description: "Помещение для бизнеса в центре города",
    location: "Санкт-Петербург",
    type: "Недвижимость",
    propertyType: "Офис",
    area: 60,
    rooms: 2,
    price: 8000000,
  },
  {
    id: 4,
    name: "Toyota Camry",
    description: "Комфортный седан в отличном состоянии",
    location: "Казань",
    type: "Авто",
    brand: "Toyota",
    model: "Camry",
    year: 2018,
    mileage: 50000,
  },
  {
    id: 5,
    name: "BMW X5",
    description: "Премиальный внедорожник с полным приводом",
    location: "Екатеринбург",
    type: "Авто",
    brand: "BMW",
    model: "X5",
    year: 2020,
    mileage: 30000,
  },
  {
    id: 6,
    name: "Lada Granta",
    description: "Экономичный автомобиль для города",
    location: "Нижний Новгород",
    type: "Авто",
    brand: "Lada",
    model: "Granta",
    year: 2015,
    mileage: 100000,
  },
  {
    id: 7,
    name: "Ремонт сантехники",
    description: "Качественный ремонт сантехники любой сложности",
    location: "Новосибирск",
    type: "Услуги",
    serviceType: "Сантехника",
    experience: 10,
    cost: 2000,
    workSchedule: "Пн-Пт, 9:00-18:00",
  },
  {
    id: 8,
    name: "Уроки английского",
    description: "Индивидуальные занятия с носителем языка",
    location: "Москва",
    type: "Услуги",
    serviceType: "Образование",
    experience: 5,
    cost: 1500,
  },
  {
    id: 9,
    name: "Фотосессия",
    description: "Профессиональная фотосессия в студии или на природе",
    location: "Санкт-Петербург",
    type: "Услуги",
    serviceType: "Фотография",
    experience: 7,
    cost: 5000,
  },
  {
    id: 10,
    name: "Квартира у моря",
    description: "Апартаменты с видом на море",
    location: "Сочи",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 70,
    rooms: 2,
    price: 15000000,
  },
  {
    id: 11,
    name: "Audi A4",
    description: "Стильный седан с минимальным пробегом",
    location: "Краснодар",
    type: "Авто",
    brand: "Audi",
    model: "A4",
    year: 2019,
    mileage: 40000,
  },
  {
    id: 12,
    name: "Ремонт компьютеров",
    description: "Настройка и ремонт ПК и ноутбуков",
    location: "Воронеж",
    type: "Услуги",
    serviceType: "IT",
    experience: 8,
    cost: 1000,
  },
  {
    id: 13,
    name: "Коттедж в лесу",
    description: "Уединенный коттедж для отдыха",
    location: "Карелия",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 200,
    rooms: 6,
    price: 30000000,
  },
  {
    id: 14,
    name: "Hyundai Solaris",
    description: "Надежный автомобиль для города",
    location: "Ростов-на-Дону",
    type: "Авто",
    brand: "Hyundai",
    model: "Solaris",
    year: 2017,
    mileage: 80000,
  },
  {
    id: 15,
    name: "Уборка квартир",
    description: "Генеральная уборка квартир и домов",
    location: "Москва",
    type: "Услуги",
    serviceType: "Клининг",
    experience: 3,
    cost: 2500,
  },
  {
    id: 16,
    name: "Mercedes-Benz E-Class",
    description: "Роскошный седан с полным комплектом опций",
    location: "Санкт-Петербург",
    type: "Авто",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2021,
    mileage: 20000,
  },
  {
    id: 17,
    name: "Юридические консультации",
    description: "Помощь в решении юридических вопросов",
    location: "Екатеринбург",
    type: "Услуги",
    serviceType: "Юриспруденция",
    experience: 12,
    cost: 3000,
  },
  {
    id: 18,
    name: "Таунхаус",
    description: "Современный таунхаус в спальном районе",
    location: "Казань",
    type: "Недвижимость",
    propertyType: "Таунхаус",
    area: 120,
    rooms: 4,
    price: 18000000,
  },
  {
    id: 19,
    name: "Kia Rio",
    description: "Экономичный и надежный автомобиль",
    location: "Уфа",
    type: "Авто",
    brand: "Kia",
    model: "Rio",
    year: 2016,
    mileage: 90000,
  },
  {
    id: 20,
    name: "Mercedes-Benz E-Class",
    description: "Роскошный седан с полным комплектом опций",
    location: "Санкт-Петербург",
    type: "Авто",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2021,
    mileage: 20000,
  },
  {
    id: 21,
    name: "Юридические консультации",
    description: "Помощь в решении юридических вопросов",
    location: "Екатеринбург",
    type: "Услуги",
    serviceType: "Юриспруденция",
    experience: 12,
    cost: 3000,
  },
  {
    id: 22,
    name: "Таунхаус",
    description: "Современный таунхаус в спальном районе",
    location: "Казань",
    type: "Недвижимость",
    propertyType: "Таунхаус",
    area: 120,
    rooms: 4,
    price: 18000000,
  },
  {
    id: 23,
    name: "Kia Rio",
    description: "Экономичный и надежный автомобиль",
    location: "Уфа",
    type: "Авто",
    brand: "Kia",
    model: "Rio",
    year: 2016,
    mileage: 90000,
  },
  {
    id: 24,
    name: "Kia Rio",
    description: "Экономичный и надежный автомобиль",
    location: "Уфа",
    type: "Авто",
    brand: "Kia",
    model: "Rio",
    year: 2016,
    mileage: 90000,
  },
  {
    id: 25,
    name: "Kia Rio",
    description: "Экономичный и надежный автомобиль",
    location: "Уфа",
    type: "Авто",
    brand: "Kia",
    model: "Rio",
    year: 2016,
    mileage: 90000,
  },
  {
    id: 26,
    name: "Квартира на окраине города",
    description: "Уютная квартира с хорошей транспортной развязкой",
    location: "Казань",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 60,
    rooms: 2,
    price: 5000000,
  },
  {
    id: 27,
    name: "Седан Honda Accord",
    description: "Комфортабельный и экономичный седан с хорошей динамикой",
    location: "Москва",
    type: "Авто",
    brand: "Honda",
    model: "Accord",
    year: 2019,
    mileage: 45000,
  },
  {
    id: 28,
    name: "Массаж и восстановление",
    description: "Профессиональный массаж с индивидуальным подходом",
    location: "Санкт-Петербург",
    type: "Услуги",
    serviceType: "Массаж",
    experience: 5,
    cost: 1500,
  },
  {
    id: 29,
    name: "Коттедж у озера",
    description: "Отличный дом для отдыха с собственным выходом к озеру",
    location: "Воронеж",
    type: "Недвижимость",
    propertyType: "Коттедж",
    area: 180,
    rooms: 4,
    price: 12000000,
  },
  {
    id: 30,
    name: "Mercedes-Benz G-Class",
    description:
      "Престижный внедорожник с полным приводом и современными технологиями",
    location: "Екатеринбург",
    type: "Авто",
    brand: "Mercedes-Benz",
    model: "G-Class",
    year: 2021,
    mileage: 20000,
  },
  {
    id: 31,
    name: "Ремонт бытовой техники",
    description:
      "Ремонт холодильников, стиральных машин, телевизоров и прочей бытовой техники",
    location: "Москва",
    type: "Услуги",
    serviceType: "Ремонт бытовой техники",
    experience: 8,
    cost: 2500,
  },
  {
    id: 32,
    name: "Дача в Подмосковье",
    description: "Уютная дача с большим участком земли",
    location: "Подмосковье",
    type: "Недвижимость",
    propertyType: "Дача",
    area: 120,
    rooms: 3,
    price: 7000000,
  },
  {
    id: 33,
    name: "BMW X6",
    description:
      "Шикарный внедорожник с мощным двигателем и комфортным салоном",
    location: "Сочи",
    type: "Авто",
    brand: "BMW",
    model: "X6",
    year: 2020,
    mileage: 30000,
  },
  {
    id: 34,
    name: "Фотосессия на природе",
    description: "Профессиональная фотосессия на свежем воздухе для всей семьи",
    location: "Краснодар",
    type: "Услуги",
    serviceType: "Фотосессия",
    experience: 6,
    cost: 4000,
  },
  {
    id: 35,
    name: "Дом с бассейном",
    description: "Современный дом с бассейном и зоной отдыха",
    location: "Ростов-на-Дону",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 250,
    rooms: 6,
    price: 30000000,
  },
  {
    id: 36,
    name: "Квартира с ремонтом в центре",
    description: "Современная квартира с ремонтом, готова к заселению",
    location: "Новосибирск",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 55,
    rooms: 2,
    price: 4500000,
  },
  {
    id: 37,
    name: "BMW 3 Series",
    description: "Элегантный седан с отличной динамикой и экономичностью",
    location: "Калуга",
    type: "Авто",
    brand: "BMW",
    model: "3 Series",
    year: 2018,
    mileage: 60000,
  },
  {
    id: 38,
    name: "Услуги по укладке плитки",
    description:
      "Профессиональная укладка плитки в ванной, на кухне и других помещениях",
    location: "Воронеж",
    type: "Услуги",
    serviceType: "Укладка плитки",
    experience: 4,
    cost: 2000,
  },
  {
    id: 39,
    name: "Коттедж с баней",
    description: "Просторный коттедж с баней и зоной для барбекю",
    location: "Калуга",
    type: "Недвижимость",
    propertyType: "Коттедж",
    area: 150,
    rooms: 4,
    price: 8000000,
  },
  {
    id: 40,
    name: "Audi Q5",
    description:
      "Элегантный кроссовер с полным приводом и современным дизайном",
    location: "Челябинск",
    type: "Авто",
    brand: "Audi",
    model: "Q5",
    year: 2017,
    mileage: 80000,
  },
  {
    id: 41,
    name: "Косметические услуги",
    description: "Профессиональные услуги по уходу за кожей лица и тела",
    location: "Тула",
    type: "Услуги",
    serviceType: "Косметология",
    experience: 3,
    cost: 1500,
  },
  {
    id: 42,
    name: "Дом на берегу моря",
    description: "Элитный дом на побережье с красивым видом на море",
    location: "Сочи",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 250,
    rooms: 5,
    price: 25000000,
  },
  {
    id: 43,
    name: "Volkswagen Golf",
    description:
      "Компактный и удобный городской автомобиль с хорошей экономией топлива",
    location: "Самара",
    type: "Авто",
    brand: "Volkswagen",
    model: "Golf",
    year: 2020,
    mileage: 30000,
  },
  {
    id: 44,
    name: "Ремонт электрооборудования",
    description:
      "Ремонт телевизоров, стиральных машин и других электроприборов",
    location: "Томск",
    type: "Услуги",
    serviceType: "Ремонт электрооборудования",
    experience: 7,
    cost: 3500,
  },
  {
    id: 45,
    name: "Дуплекс в центре города",
    description: "Роскошный дуплекс с панорамным видом на город",
    location: "Казань",
    type: "Недвижимость",
    propertyType: "Дуплекс",
    area: 120,
    rooms: 3,
    price: 12000000,
  },
  {
    id: 46,
    name: "Honda CR-V",
    description:
      "Просторный и надежный кроссовер с высоким уровнем безопасности",
    location: "Ростов-на-Дону",
    type: "Авто",
    brand: "Honda",
    model: "CR-V",
    year: 2019,
    mileage: 50000,
  },
  {
    id: 47,
    name: "Услуги по укладке ламината",
    description: "Укладка качественного ламината с гарантией",
    location: "Калуга",
    type: "Услуги",
    serviceType: "Укладка ламината",
    experience: 5,
    cost: 1800,
  },
  {
    id: 48,
    name: "Загородный дом с сауной",
    description: "Большой загородный дом с сауной и садом",
    location: "Воронеж",
    type: "Недвижимость",
    propertyType: "Дом",
    area: 200,
    rooms: 5,
    price: 15000000,
  },
  {
    id: 49,
    name: "Nissan X-Trail",
    description: "Проходимый внедорожник с отличными внедорожными качествами",
    location: "Пермь",
    type: "Авто",
    brand: "Nissan",
    model: "X-Trail",
    year: 2018,
    mileage: 70000,
  },
  {
    id: 50,
    name: "Ремонт компьютеров и ноутбуков",
    description: "Профессиональная настройка и ремонт компьютеров и ноутбуков",
    location: "Томск",
    type: "Услуги",
    serviceType: "Ремонт компьютеров",
    experience: 6,
    cost: 2500,
  },
  {
    id: 51,
    name: "Коттедж в лесу",
    description: "Уединенный коттедж в лесной зоне с большим участком земли",
    location: "Курск",
    type: "Недвижимость",
    propertyType: "Коттедж",
    area: 180,
    rooms: 4,
    price: 9500000,
  },
  {
    id: 52,
    name: "Mitsubishi Outlander",
    description:
      "Популярный кроссовер с вместительным салоном и хорошей управляемостью",
    location: "Ставрополь",
    type: "Авто",
    brand: "Mitsubishi",
    model: "Outlander",
    year: 2021,
    mileage: 25000,
  },
  {
    id: 53,
    name: "Услуги по ремонту электрики",
    description: "Профессиональный ремонт электрики в квартирах и домах",
    location: "Краснодар",
    type: "Услуги",
    serviceType: "Ремонт электрики",
    experience: 7,
    cost: 3000,
  },
  {
    id: 54,
    name: "Квартира в новом доме",
    description: "Просторная квартира в новом жилом комплексе с ремонтом",
    location: "Казань",
    type: "Недвижимость",
    propertyType: "Квартира",
    area: 80,
    rooms: 3,
    price: 7500000,
  },
  {
    id: 55,
    name: "Toyota Camry",
    description:
      "Комфортабельный седан с высоким уровнем оснащения и безопасности",
    location: "Ростов-на-Дону",
    type: "Авто",
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    mileage: 15000,
  },
  {
    id: 56,
    name: "Услуги по стрижке и укладке",
    description:
      "Профессиональная стрижка и укладка волос с индивидуальным подходом",
    location: "Сочи",
    type: "Услуги",
    serviceType: "Парикмахерские услуги",
    experience: 4,
    cost: 1200,
  },
];

module.exports = { items };
